/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "cpu.v:3.1-100.10" *)
module cpu_top(clk, reset);
  (* src = "cpu.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "cpu.v:77.17-77.31" *)
  wire [31:0] pc_jalr_target;
  (* src = "cpu.v:5.17-5.22" *)
  input reset;
  wire reset;
  assign pc_jalr_target = 32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0;
endmodule
